const encoder=new TextEncoder()
const utf8=v=>encoder.encode(String(v??''))
const xe=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')
const slug=v=>String(v||'scenario-veille').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,72)||'scenario-veille'
const today=()=>new Date().toISOString().slice(0,10)
function crc32(bytes){let crc=0^-1;for(let i=0;i<bytes.length;i++){crc^=bytes[i];for(let j=0;j<8;j++)crc=(crc>>>1)^(0xEDB88320&-(crc&1))}return(crc^-1)>>>0}
function u16(n){const b=new Uint8Array(2);new DataView(b.buffer).setUint16(0,n,true);return b}function u32(n){const b=new Uint8Array(4);new DataView(b.buffer).setUint32(0,n>>>0,true);return b}
function concat(parts){const total=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(total);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function buildZip(files){const locals=[],central=[];let offset=0;for(const[name,content]of Object.entries(files)){const nb=utf8(name),data=content instanceof Uint8Array?content:utf8(content),crc=crc32(data);const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nb.length),u16(0),nb,data]);locals.push(local);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nb]));offset+=local.length}const cb=concat(central);return concat([...locals,cb,concat([u32(0x06054b50),u16(0),u16(0),u16(central.length),u16(central.length),u32(cb.length),u32(offset),u16(0)])])}
function download(bytes,name,mime){const blob=new Blob([bytes],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}

function fmtRep(v=''){const raw=String(v||'').trim();if(!raw)return'';if(/^\d+\s*[;,]\s*\d+$/.test(raw)){const[a,b]=raw.split(/[;,]/).map(x=>x.trim());return a===b?`p. ${a}`:`p. ${a}–${b}`}if(/^\d+\s*[-–]\s*\d+$/.test(raw)){const[a,b]=raw.split(/[-–]/).map(x=>x.trim());return a===b?`p. ${a}`:`p. ${a}–${b}`}if(/^\d+$/.test(raw))return`p. ${raw}`;return`repère ${raw}`}
function sourceHref(s={}){const raw=String(s.url||'').trim();if(!raw)return'';const first=(String(s.repere||'').match(/\d+/)||[])[0];return /\.pdf(?:$|[?#])/i.test(raw)&&first?`${raw.split('#')[0]}#page=${first}`:raw}
function clean(v=''){return String(v||'').replace(/\bM\d+\b(?:\s*(?:,|et|ou)\s*M\d+\b)*/gi,'les matériaux retenus').replace(/les matériaux\s+les matériaux retenus/gi,'les matériaux retenus').replace(/\s+/g,' ').trim()}
function run(text,{bold=false,italic=false,color='',size=22,font='Aptos'}={}){return `<w:r><w:rPr><w:rFonts w:ascii="${font}" w:hAnsi="${font}"/>${bold?'<w:b/>':''}${italic?'<w:i/>':''}${color?`<w:color w:val="${color}"/>`:''}${size?`<w:sz w:val="${size}"/>`:''}</w:rPr><w:t xml:space="preserve">${xe(text)}</w:t></w:r>`}
function p(inner,{style='',before=0,after=100,align='',keep=false,shade='',borderBottom=''}={}){return `<w:p><w:pPr>${style?`<w:pStyle w:val="${style}"/>`:''}<w:spacing w:before="${before}" w:after="${after}"/>${align?`<w:jc w:val="${align}"/>`:''}${keep?'<w:keepNext/>':''}${shade?`<w:shd w:val="clear" w:color="auto" w:fill="${shade}"/>`:''}${borderBottom?`<w:pBdr><w:bottom w:val="single" w:sz="6" w:space="5" w:color="${borderBottom}"/></w:pBdr>`:''}</w:pPr>${inner}</w:p>`}
function pageBreak(){return '<w:p><w:r><w:br w:type="page"/></w:r></w:p>'}
function bullet(text){return `<w:p><w:pPr><w:pStyle w:val="Bullet"/><w:ind w:left="360" w:hanging="180"/><w:spacing w:after="70"/></w:pPr>${run('•  ',{bold:true,color:'1768C4',size:20})}${run(clean(text),{size:20,color:'405D77'})}</w:p>`}
function cell(inner,{fill='FFFFFF',width=9000,margin=180}={}){return `<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/><w:shd w:val="clear" w:color="auto" w:fill="${fill}"/><w:tcMar><w:top w:w="${margin}" w:type="dxa"/><w:left w:w="${margin}" w:type="dxa"/><w:bottom w:w="${margin}" w:type="dxa"/><w:right w:w="${margin}" w:type="dxa"/></w:tcMar></w:tcPr>${inner}</w:tc>`}
function oneCell(inner,fill='FFFFFF'){return `<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/><w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="9000"/></w:tblGrid><w:tr>${cell(inner,{fill})}</w:tr></w:tbl>`}
function linkRun(text,rId){return `<w:hyperlink r:id="${rId}" w:history="1"><w:r><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:color w:val="1768C4"/><w:u w:val="single"/><w:b/><w:sz w:val="18"/></w:rPr><w:t>${xe(text)}</w:t></w:r></w:hyperlink>`}
function sourceParas(s,links){const ref=[s.publication_id,fmtRep(s.repere),s.titre].filter(Boolean).join(' — ');let out=p(run(ref||'Source du corpus',{bold:true,color:'315F8F',size:18}),{after:30});const href=sourceHref(s);if(href){const id=`rId${links.length+10}`;links.push({id,url:href});out+=p(linkRun('Ouvrir la source ↗',id),{after:70})}return out}
function objectBlock(item,type,links){const body=type==='trend'?item.synthese:type==='watch'?item.pourquoi_guetter:item.raison;let inner=p(run(item.label||'',{bold:true,color:'173F67',size:21}),{after:55,keep:true});if(body)inner+=p(run(clean(body),{color:'405D77',size:19}),{after:65});if(type==='trend'&&item.limite)inner+=p(run(`Limite : ${clean(item.limite)}`,{italic:true,color:'7A6372',size:18}),{after:55});for(const s of item.sources||[])inner+=sourceParas(s,links);return oneCell(inner,'F8FBFE')}
function categorySection(title,items,type,empty,links,color){let out=p(run(title,{bold:true,color,size:23}),{before:150,after:80,keep:true,borderBottom:'D7E5F1'});if(!items?.length)return out+oneCell(p(run(empty,{italic:true,color:'71869A',size:19}),{after:0}),'FAFCFE');for(const item of items)out+=objectBlock(item,type,links);return out}

export function buildScenarioDocx(result={}){
  const need=String(result.need||result.need_original||'').trim(), axes=result.axes||[], objects=result.objects||result.watch||[], links=[]
  const longDate=new Intl.DateTimeFormat('fr-FR',{dateStyle:'long'}).format(new Date())
  let body=''
  body+=oneCell(p(run('QUIRITÈS VEILLE LAB',{bold:true,color:'AEE9DF',size:18}),{after:150})+p(run('Scénario de veille',{bold:true,color:'FFFFFF',size:44,font:'Georgia'}),{after:160})+p(run(need,{color:'FFFFFF',size:26,font:'Georgia'}),{after:180})+p(run(`Généré le ${longDate}`,{color:'D6E6F5',size:18}),{after:0}),'082653')
  body+=p(run('Repères de lecture',{bold:true,color:'1768C4',size:22}),{before:240,after:80})
  body+=p(run('Le scénario distingue les tendances suffisamment documentées, les éléments à surveiller et les sources dont le caractère récurrent est établi par le corpus. Une rubrique peut rester vide si les matériaux ne permettent pas de conclure.',{color:'4E6A86',size:20}),{after:160})
  body+=p(run('Axes retenus',{bold:true,color:'0B315E',size:28,font:'Georgia'}),{before:120,after:90})
  axes.forEach((a,i)=>{body+=p(run(`${i+1}. ${a.titre||a.title||''}`,{bold:true,color:'17466F',size:21}),{after:35});if(a.objectif_surveillance||a.objective)body+=p(run(a.objectif_surveillance||a.objective,{color:'607A91',size:19}),{after:75})})
  body+=pageBreak()

  objects.forEach((o,i)=>{
    if(i>0)body+=pageBreak()
    const title=o.titre||o.axis_title||axes[i]?.titre||'Axe de veille', objective=o.objectif_surveillance||axes[i]?.objectif_surveillance||''
    body+=p(run(`AXE ${i+1}`,{bold:true,color:'1768C4',size:18}),{after:40})
    body+=p(run(title,{bold:true,color:'0B315E',size:32,font:'Georgia'}),{after:70,keep:true})
    if(objective)body+=p(run(objective,{italic:true,color:'58738F',size:21}),{after:150})
    if(o.statut&&o.statut!=='ok'){body+=oneCell(p(run(o.message||'Aucun objet suffisamment sourcé.',{italic:true,color:'71869A',size:20}),{after:0}),'FAFCFE');return}
    body+=categorySection('Tendances documentées',o.tendances||o.trends,'trend','Aucune tendance suffisamment documentée.',links,'1768C4')
    body+=categorySection('Éléments à surveiller',o.signes_a_guetter||o.watch_signs,'watch','Aucun élément suffisamment sourcé.',links,'07846F')
    body+=categorySection('Sources à surveiller',o.sources_a_surveiller||o.sources_to_watch,'source','Aucune source récurrente identifiée.',links,'7047C8')
    const points=o.angles_morts||o.points_to_document||[]
    body+=p(run('Points à documenter',{bold:true,color:'315F8F',size:23}),{before:170,after:80,borderBottom:'D7E5F1'})
    if(points.length){for(const x of points)body+=bullet(x)}else body+=p(run('Aucun point supplémentaire identifié.',{italic:true,color:'71869A',size:19}),{after:60})
  })
  body+=pageBreak()+oneCell(p(run('Quiritès Veille Lab',{bold:true,color:'FFFFFF',size:28,font:'Georgia'}),{after:90})+p(run('Fiabilité > exhaustivité',{bold:true,color:'AEE9DF',size:22}),{after:80})+p(run('Chaque objet est conservé uniquement lorsqu’il dispose d’un appui documentaire vérifiable dans le corpus actif. Les provenances permettent de revenir aux publications et aux pages mobilisées.',{color:'E5EEF6',size:20}),{after:0}),'082653')

  const documentXml=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="900" w:right="900" w:bottom="900" w:left="900" w:header="500" w:footer="500"/></w:sectPr></w:body></w:document>`
  const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Aptos" w:hAnsi="Aptos"/><w:sz w:val="20"/><w:lang w:val="fr-FR"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style><w:style w:type="paragraph" w:styleId="Bullet"><w:name w:val="Bullet"/></w:style></w:styles>`
  const docRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>${links.map(x=>`<Relationship Id="${x.id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xe(x.url)}" TargetMode="External"/>`).join('')}</Relationships>`
  const rootRels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`
  const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`
  const now=new Date().toISOString(),core=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>Scénario de veille</dc:title><dc:creator>Quiritès Veille Lab</dc:creator><dcterms:created xsi:type="dcterms:W3CDTF">${now}</dcterms:created></cp:coreProperties>`,app=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>Quiritès Veille Lab</Application></Properties>`
  return buildZip({'[Content_Types].xml':types,'_rels/.rels':rootRels,'word/document.xml':documentXml,'word/styles.xml':styles,'word/_rels/document.xml.rels':docRels,'docProps/core.xml':core,'docProps/app.xml':app})
}
export function exportScenarioWord(result){download(buildScenarioDocx(result),`Scenario_de_veille_${slug(result?.need||result?.need_original)}_${today()}.docx`,'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}
